[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
address = "0.0.0.0"
maxUploadSize = 200
runOnSave = false
fileWatcherType = "none"

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[runner]
magicEnabled = false
fastReruns = true